name: Release
on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8.0.372+7
          cache: sbt
          gpg-private-key: ${{ secrets.PGP_SECRET }}
          gpg-passphrase: PGP_PASSPHRASE
      - run: git config user.email "release-bot@sbt.github.com"
      - run: git config user.name "sbt release bot"
      - name: Push tag
        run: sbt "release with-defaults"
